require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'test/**/*'