require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Style/Documentation:
  Exclude:
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/WordArray:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false
