require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Capybara/NegationMatcher:
  EnforcedStyle: not_to

Capybara/RSpec/HaveSelector:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/**/*'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'db/**/*'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'
    - 'app/models/user.rb'

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/ReceiveMessages:
  Enabled: false

RSpec/Rails/NegationBeValid:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/NumericLiterals:
  # Permit integers representing timestamps
  # ex. 2023_08_13_19_05_25 (for comparing ActiveRecord Migration versions)
  AllowedPatterns:
    - '\d{4}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}'

Style/OpenStructUse:
  Exclude:
    - 'spec/helpers/t3_form_builder_spec.rb'

Style/RedundantReturn:
  Exclude:
    - 'app/models/custom_domain.rb'

Style/SymbolProc:
  AllowedPatterns: ['map', 'select']

Style/WordArray:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false
