require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable

Rails/I18nLocaleTexts:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/20230412212141_add_blueprint_to_works.rb'

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'test/**/*'