require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/blueprints' do
  # This should return the minimal set of attributes required to create a valid
  # Blueprint. As you add validations to Blueprint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { name: 'sample_blueprint' } }

  let(:invalid_attributes) { { name: 'bad &^%#@! blueprint!' } }

  describe 'GET /index' do
    it 'renders a successful response' do
      Blueprint.create! valid_attributes
      get blueprints_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      blueprint = Blueprint.create! valid_attributes
      get blueprint_url(blueprint)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_blueprint_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      blueprint = Blueprint.create! valid_attributes
      get edit_blueprint_url(blueprint)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Blueprint' do
        expect do
          post blueprints_url, params: { blueprint: valid_attributes }
        end.to change(Blueprint, :count).by(1)
      end

      it 'redirects to the created blueprint' do
        post blueprints_url, params: { blueprint: valid_attributes }
        expect(response).to redirect_to(blueprint_url(Blueprint.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Blueprint' do
        expect do
          post blueprints_url, params: { blueprint: invalid_attributes }
        end.not_to change(Blueprint, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post blueprints_url, params: { blueprint: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) { { name: 'renamed_blueprint' } }

      it 'updates the requested blueprint' do
        blueprint = Blueprint.create! valid_attributes
        patch blueprint_url(blueprint), params: { blueprint: new_attributes }
        blueprint.reload
        expect(blueprint.name).to eq 'renamed_blueprint'
      end

      it 'redirects to the blueprint' do
        blueprint = Blueprint.create! valid_attributes
        patch blueprint_url(blueprint), params: { blueprint: new_attributes }
        blueprint.reload
        expect(response).to redirect_to(blueprint_url(blueprint))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        blueprint = Blueprint.create! valid_attributes
        patch blueprint_url(blueprint), params: { blueprint: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested blueprint' do
      blueprint = Blueprint.create! valid_attributes
      expect do
        delete blueprint_url(blueprint)
      end.to change(Blueprint, :count).by(-1)
    end

    it 'redirects to the blueprints list' do
      blueprint = Blueprint.create! valid_attributes
      delete blueprint_url(blueprint)
      expect(response).to redirect_to(blueprints_url)
    end
  end
end
